name: hesab_ban
description: The accounting Hesab Ban application is suitable for people who do not have access to a computer or laptop and can invoice, check and check the customer's account with a mobile phone.

publish_to: 'none'

version: 2.2.4+1036

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.1
  persian_number_utility: ^1.1.1
  hive: ^2.1.0
  hive_flutter: 1.1.0
  lottie: ^3.1.0
  cached_network_image: ^3.2.0
  animations: ^2.0.2
  sliver_tools: ^0.2.12
  persian_datetime_picker: ^2.4.0
  url_launcher: ^6.0.11
  currency_text_input_formatter: ^2.1.5
  pdf: ^3.7.3
  printing: ^5.7.4
  image_picker: ^1.0.7
  image_cropper: ^5.0.0
  open_file: ^3.2.1
  flutter_local_notifications: ^16.1.0
  flutter_time_picker_spinner: ^2.0.0
  json_annotation: ^4.4.0
  archive: ^3.4.9
  google_sign_in: ^6.1.4
  googleapis: ^12.0.0
  http: ^1.1.0
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  animated_bottom_navigation: ^0.0.5
  iconsax: ^0.0.8
  share_plus: ^7.1.0
  dropdown_button2: ^2.1.3
  collection: any
  path_provider: any
  image: ^4.0.17
  timezone: ^0.9.2
  dio: ^5.3.3
  package_info_plus: ^5.0.1
  barcode_widget: ^2.0.4
  reorderables: ^0.6.0
  appcheck: ^1.0.6
  local_auth: ^2.1.7
  crypto: ^3.0.3
  html: ^0.15.4
  flutter_flavor: ^3.1.3
  flutter_svg: ^2.0.10+1
  local_auth_android: ^1.0.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.9
  json_serializable: ^6.1.6
  flutter_lints: ^3.0.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/banks_image/
    - assets/fonts/

  fonts:
    - family: Yekan
      fonts:
        - asset: assets/fonts/IRANYekan_Regular.ttf
        - asset: assets/fonts/IRANYekan_Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANYekan_Black.ttf
          weight: 900
